services:
  - type: web
    name: neuronetwork
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 120
    envVars:
      - key: NEO4J_URI
        value: bolt+s://4e5eeae5.databases.neo4j.io:7687
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        value: Poconoco16!
