services:
  - type: web
    name: neurotome
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: NEO4J_URI
        value: bolt+s://4e5eeae5.databases.neo4j.io:7687
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
